### PR TITLE
Chat with LM Studio with Voice!

### PR DESCRIPTION
**Pull request by BBC-Esq**

### CODE REVIEW

**Comment by BBC-Esq** [comment]
Added to this pull request.  Please review and let me know!

**Comment by yagil** [comment]
Super cool work!

**Review by yagil — APPROVED** [review]

**Comment by yagil** [comment]
@BBC-Esq I merged this, but now I think it might be incomplete?  I don't see any part that interacts with LM Studio's API, unless I'm missing something obvious. Let me know

**Comment by BBC-Esq** [comment]
> @BBC-Esq I merged this, but now I think it might be incomplete? I don't see any part that interacts with LM Studio's API, unless I'm missing something obvious. Let me know
> 
> Edit: Might be just that the documentation needs to make it clearer what this is and how you're supposed to use it with LM Studio.

Will do.  The idea was to transcribe audio that can be pasted into the prompt box within lm studio (or anything else really).

**Pull request merged**
